// <auto-generated />
using System;
using AgroTemp.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroTemp.Domain.Migrations
{
    [DbContext(typeof(AgroTempDbContext))]
    [Migration("20260323101010_AddRelatedEntityIdToNotification")]
    partial class AddRelatedEntityIdToNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AgroTempV1")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroTemp.Domain.Entities.BlacklistedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blacklisted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_id");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedToken", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Chat_Message", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_name");

                    b.Property<string>("ExpoPushToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expo_push_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasColumnName("platform");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpoPushToken")
                        .IsUnique();

                    b.ToTable("DeviceToken", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.DisputeReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisputeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("dispute_type");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text")
                        .HasColumnName("evidence_url");

                    b.Property<Guid?>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_post_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedById")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("JobPostId");

                    b.HasIndex("ResolvedById");

                    b.HasIndex("WorkerId");

                    b.ToTable("dispute_reports", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<decimal?>("AreaSize")
                        .HasColumnType("numeric")
                        .HasColumnName("area_size");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FarmType")
                        .HasColumnType("integer")
                        .HasColumnName("farm_type");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<int?>("LivestockCount")
                        .HasColumnType("integer")
                        .HasColumnName("livestock_count");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location_name");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farm", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Farmer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("TotalJobsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_completed");

                    b.Property<int>("TotalJobsPosted")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_posted");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Farmer", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_post_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text")
                        .HasColumnName("response_message");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Job_Application", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<Guid>("JobDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_detail_id");

                    b.HasKey("Id");

                    b.HasIndex("JobDetailId");

                    b.ToTable("job_attachment", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Job_Category", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FarmerApprovedPercent")
                        .HasColumnType("integer")
                        .HasColumnName("farmer_approved_percent");

                    b.Property<string>("FarmerFeedback")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farmer_feedback");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_application_id");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_post_id");

                    b.Property<decimal>("JobPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("job_price");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WorkDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("work_date");

                    b.Property<string>("WorkerDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("worker_description");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<decimal?>("WorkerPaymentAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("worker_payment_amount");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("JobPostId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Job_Detail", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<Guid>("JobCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_category_id");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("job_type");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferences");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_skills");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("wage_amount");

                    b.Property<int>("WorkersAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("workers_accepted");

                    b.Property<int>("WorkersNeeded")
                        .HasColumnType("integer")
                        .HasColumnName("workers_needed");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("Job_Post", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobSkillRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_post_id");

                    b.Property<int>("RequiredLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("required_level");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("SkillId");

                    b.ToTable("Job_Skill_Requirement", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeOfTax")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_of_tax");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("IssuedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_datetime");

                    b.Property<long?>("IssuedTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_timestamp");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ReservationCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reservation_code");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PayOS_Invoice", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_number");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paid");

                    b.Property<long>("AmountRemaining")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_remaining");

                    b.Property<string>("Bin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bin");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("text")
                        .HasColumnName("buyer_address");

                    b.Property<string>("BuyerCompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("buyer_company_name");

                    b.Property<string>("BuyerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("buyer_name");

                    b.Property<bool?>("BuyerNotGetInvoice")
                        .HasColumnType("boolean")
                        .HasColumnName("buyer_not_get_invoice");

                    b.Property<string>("BuyerPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("buyer_phone");

                    b.Property<string>("CancelUrl")
                        .HasColumnType("text")
                        .HasColumnName("cancel_url");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkout_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTime?>("LastTransactionUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transaction_update");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_link_id");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("text")
                        .HasColumnName("return_url");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<int?>("TaxPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("tax_percentage");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("PaymentLinkId");

                    b.ToTable("PayOS_Order", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("TaxPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("tax_percentage");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PayOS_Order_Item", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_number");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("CounterAccountBankId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("counter_account_bank_id");

                    b.Property<string>("CounterAccountBankName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("counter_account_bank_name");

                    b.Property<string>("CounterAccountName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("counter_account_name");

                    b.Property<string>("CounterAccountNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("counter_account_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_datetime");

                    b.Property<string>("VirtualAccountName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("virtual_account_name");

                    b.Property<string>("VirtualAccountNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("virtual_account_number");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PayOS_Transaction", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSWebhookLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsPayloadParsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_payload_parsed");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<long?>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("Reference");

                    b.ToTable("PayOS_Webhook_Log", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkout_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymnetLink_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Payments", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("RateeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ratee_id");

                    b.Property<Guid>("RaterId")
                        .HasColumnType("uuid")
                        .HasColumnName("rater_id");

                    b.Property<int>("RatingScore")
                        .HasColumnType("integer")
                        .HasColumnName("rating_score");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("RateeId");

                    b.HasIndex("RaterId");

                    b.ToTable("Rating", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Skill", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_token_expires_at");

                    b.HasKey("Id");

                    b.ToTable("User", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LockedBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("locked_balance");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desription");

                    b.Property<Guid?>("JobDetailId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("job_detaid_id");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("JobDetailId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_holder_name");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WithdrawalRequests", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age_range");

                    b.Property<string>("AvailabilitySchedule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("availability_schedule");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExperienceLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("experience_level");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("PrimaryLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_location");

                    b.Property<int>("TotalJobsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_completed");

                    b.Property<double?>("TravelRadiusKmPreference")
                        .HasColumnType("double precision")
                        .HasColumnName("travel_radius_km_preference");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Worker", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WorkerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("CheckInNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("check_in_notes");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<string>("CheckOutNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("check_out_notes");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<Guid>("JobDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_detail_id");

                    b.Property<decimal?>("TotalHoursWorked")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_hours_worked");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("JobDetailId");

                    b.ToTable("Worker_Session", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WorkerSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ProficiencyLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Worker_Skill", "AgroTempV1");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.User", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.DisputeReport", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId");

                    b.HasOne("AgroTemp.Domain.Entities.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.User", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedById");

                    b.HasOne("AgroTemp.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId");

                    b.Navigation("Farmer");

                    b.Navigation("JobPost");

                    b.Navigation("ResolvedBy");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Farm", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Farmer", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.User", "User")
                        .WithOne("Farmer")
                        .HasForeignKey("AgroTemp.Domain.Entities.Farmer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobAttachment", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobDetail", "JobDetail")
                        .WithMany("JobAttachments")
                        .HasForeignKey("JobDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDetail");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobDetail", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany("JobDetails")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.JobPost", "JobPost")
                        .WithMany("JobDetails")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Worker", "Worker")
                        .WithMany("JobDetails")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("JobPost");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobPost", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.JobCategory", "JobCategory")
                        .WithMany("JobPosts")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Farmer");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobSkillRequirement", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobPost", "JobPost")
                        .WithMany("JobSkillRequirements")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkillRequirements")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSInvoice", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.PayOSOrder", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSOrderItem", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.PayOSOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSTransaction", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.PayOSOrder", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Payment", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Payments")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Rating", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobPost", "JobPost")
                        .WithMany("Ratings")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.User", "Ratee")
                        .WithMany("ReceivedRatings")
                        .HasForeignKey("RateeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.User", "Rater")
                        .WithMany("GivenRatings")
                        .HasForeignKey("RaterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Ratee");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("AgroTemp.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobDetail", "JobDetail")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("JobDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDetail");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Wallet", "Wallet")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Worker", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.User", "User")
                        .WithOne("Worker")
                        .HasForeignKey("AgroTemp.Domain.Entities.Worker", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WorkerSession", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.JobDetail", "JobDetail")
                        .WithMany("WorkerSessions")
                        .HasForeignKey("JobDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDetail");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.WorkerSkill", b =>
                {
                    b.HasOne("AgroTemp.Domain.Entities.Skill", "Skill")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroTemp.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Farmer", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("JobDetails");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobCategory", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobDetail", b =>
                {
                    b.Navigation("JobAttachments");

                    b.Navigation("WalletTransactions");

                    b.Navigation("WorkerSessions");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.JobPost", b =>
                {
                    b.Navigation("JobDetails");

                    b.Navigation("JobSkillRequirements");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.PayOSOrder", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Items");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkillRequirements");

                    b.Navigation("WorkerSkills");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("Farmer");

                    b.Navigation("GivenRatings");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("ReceivedRatings");

                    b.Navigation("SentMessages");

                    b.Navigation("Wallet");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("WalletTransactions");

                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("AgroTemp.Domain.Entities.Worker", b =>
                {
                    b.Navigation("JobDetails");

                    b.Navigation("WorkerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
